version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
  banking_api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=postgresql://username:password@db:5432/banking
